language: python
python:
 - "3.3"
 - "3.4"

env:
  - DATABASE_URL='postgresql://postgres:@localhost:5432/my_db'

  matrix:
   - DJANGO="Django<1.9"

services:
  - postgresql

addons:
  postgresql: "9.3"

before_install:
  - sudo apt-get update -qq
  - sudo apt-get install -y git curl autoconf automake build-essential python-virtualenv
  - sudo apt-get install -y postgresql libpq-dev
  - sudo apt-get install -y python3-dev libxslt1-dev libcairo2 shared-mime-info
  - sudo apt-get install -y libpango1.0-0 libgdk-pixbuf2.0-0 libffi-dev
  - sudo apt-get install -y libtiff4-dev libjpeg8-dev zlib1g-dev libfreetype6-dev
  - sudo apt-get install -y liblcms2-dev libwebp-dev tcl8.5-dev tk8.5-dev
  - sudo apt-get install -y libxml2 libxml2-dev libxslt-dev python3-setuptools
  - sudo easy_install3 pip

install:
  - pip3 install -r requirements/local.txt
  - pip3 install python-coveralls
  - pip3 install coverage

before_script:
  - psql -c 'create database my_db;' -U postgres

script:
  - python manage.py check
  - python manage.py migrate --noinput
  - coverage run --source='.' manage.py test crm_core
  - coverage report
after_success:
  - coveralls
